### ISSUE TITLE
Write a Function in PYTHON to achieve below functionality ( Count Complete Tree Nodes)

### ISSUE THREAD

**Issue by sayak2k1maruti** [sayak2k1maruti/competetivePogramming#45]
# Count Complete Tree Nodes
## What to Do?
 - Go to folder: "/CP/LeetCode/Count Complete Tree Nodes/"
 - Take your GitHUB username id like "hrithik339", "hacker-boy", etc or anything which you have.
 - File extension = ".py" in this issue.

## Problem:
Given the root of a complete binary tree, return the number of the nodes in the tree.

According to Wikipedia, every level, except possibly the last, is completely filled in a complete binary tree, and all nodes in the last level are as far left as possible. It can have between 1 and 2h nodes inclusive at the last level h.

Design an algorithm that runs in less than O(n) time complexity.

## Constraints
The number of nodes in the tree is in the range [0, 5 * 104].
0 <= Node.val <= 5 * 104
The tree is guaranteed to be complete.

## Example 1:
```
Input: root = [1,2,3,4,5,6]
Output: 6

```
## Example 2:
 ```
Input: root = []
Output: 0
```

## Example 3:
```
Input: root = [1]
Output: 1
```

# Template Function : 

- ## C++:
```
class Solution {
public:
    int countNodes(TreeNode* root) {
        
    }
};
```

**Comment by sayak2k1maruti** [comment]
No need to wait for getting assigned. Just go ahead and Raise PRs after doing the needed code.

**Comment by Harshgupta5901** [comment]
@sayak2k1maruti pls check #46

**Comment by arj0389** [comment]
Hi, can multiple people work on an issue, would that count as a contribution towards the fest?

**Comment by sayak2k1maruti** [comment]
> Hi, can multiple people work on an issue, would that count as a contribution towards the fest?

Yes ofcourse , you just PR your approach.
File name should be <yourUername>. extension.  If your solution is valid and accepted by corresponding platform then it will count as a contribution towards fest
