### ISSUE TITLE
Write a function in CPP or Python to achieve below functionality ( Longest Pallindromic Substring ) 

### ISSUE THREAD

**Issue by sayak2k1maruti** [sayak2k1maruti/competetivePogramming#78]
# What to Do?
## Location
* Go to folder **_CP/LeetCode/Longest Palindromic Substring_**
## File name
*    Take your GitHub username id like "hrithik339", "hacker-boy", etc or anything which you have.
*   Then add a programming language extension after this (link for C++ add .cpp and for python add.py)
    Only files with the correct file name will be accepted

# Problem -  Longest Palindromic Substring
## Problem
Given a string s, return the longest palindromic substring in s.

A string is called a palindrome string if the reverse of that string is the same as the original string.

## Example 1:
```
Input: s = "babad"
Output: "bab"
Explanation: "aba" is also a valid answer.
```
## Example 2:
```
Input: s = "cbbd"
Output: "bb"
```

## Constraints
*   1 <= s.length <= 1000
*   s consist of only digits and English letters.

**Comment by lucy2512** [comment]
I would like to work on this.
Will you please assign it to me?

**Comment by aniket2003** [comment]
@sayak2k1maruti  I would like to work on this as I have a good hold on competitive programming , so could you please Assign me with this .

**Comment by sourav9599** [comment]
can i work on this

**Comment by asv02** [comment]
@sayak2k1maruti  I can give an efficient solution with explanations, please assign it to me.

**Comment by aryanayush012** [comment]
i would like to contribute. please assign this to me
